- name: Install docker
  become: yes
  hosts: localhost
  tasks:
    - name: Install docker.io
      apt:
        name: docker.io
        update-cache: yes
        state: present
    - name: Add permission to user
      shell: |
        sudo usermod -aG docker ubuntu
        newgrp docker
    - name: print message
      debug:
        msg: "Docker installed successfully."
