name: Debug Checkout

on:
  push:
    branches: ["main"]

jobs:
  test-checkout:
    runs-on: self-hosted
    steps:
      - name: print message
        run: echo "Hello Sharvari" 
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -la
