name: Docker CICD pipeline
on:
  push:
    paths:
      - test.txt
  pull_request:
    branches: ["main"]
  
jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ansible and python3
        run: |
          sudo apt update
          sudo apt install python3 -y
          sudo apt install ansible -y 
      - name: Install docker
        run: ansible-playbook ansible/install_docker.yaml
      - name: Build docker image
        run: docker build -t hello-app:latest .
      - name: Push docker image to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag hello-app:latest $DOCKER_USERNAME/hello-app:latest
          docker push $DOCKER_USERNAME/hello-app:latest
      - name: Deploy container
        run: |
          docker pull $DOCKER_USERNAME/hello-app:latest
          docker run -d --name hello-app -p 5000:5000 $DOCKER_USERNAME/hello-app:latest
      - name: Print message
        run: echo "CICD pipeline executed successfully."
