name: Docker CICD pipeline
on:
  push:
    branches: ["main"]
    paths:
      - test.txt
  pull_request:
    branches: ["main"]
  
jobs:
  build-test-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install python3 and pip
        run: |
          sudo apt update
          sudo apt install python3 python3-pip python3.12-venv -y
      - name: Install dependencies and run tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          pytest -v
      - name: Build docker image
        run: sudo docker build -t hello-app:latest .
      - name: Push docker image to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
          sudo docker tag hello-app:latest $DOCKER_USERNAME/hello-app:latest
          sudo docker push $DOCKER_USERNAME/hello-app:latest
      - name: Deploy container
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          sudo docker pull $DOCKER_USERNAME/hello-app:latest
          sudo docker run -d --name hello-app -p 5000:5000 $DOCKER_USERNAME/hello-app:latest
      - name: Print message
        run: echo "CICD pipeline executed successfully."
